---
- name: NTP Server Configuration
  ansible.windows.win_command:
    cmd: "w32tm /config /syncfromflags:manual /manualpeerlist:'{{ ntp_servers }}'"

- name: Time Zone Configuration
  ansible.windows.win_timezone:
    timezone: "{{ time_zone }}"