---
- name: Region Settings Configuration
  ansible.windows.win_region:
    location: 39
    format: en-CA
  register: region_settings

- name: Reboot to Apply Region Settings
  ansible.windows.win_reboot:
  when: region_settings.restart_required