---
- name: Hostname Update
  ansible.windows.win_hostname:
    name: "{{ computer_name }}"
  register: result

- name: Reboot to Apply Hostname Change
  ansible.windows.win_reboot:
  when: result.reboot_required